### ISSUE TITLE
[Gemstone] Add bech32 address converter

### ISSUE THREAD

**Issue by gemcoder21** [gemwalletcom/core#135]
Implement function to convert cosmos like address to another chain address with prefix

### Example

Input: `cosmos1h3laqcrmul79zwtw6j63ncsl0adfj07wgupylj`
HRP: `osmosis`

Output: `osmosis1h3laqcrmul79zwtw6j63ncsl0adfj07wm8vf00`

**Comment by kehiy** [comment]
@gemcoder21 assigned it to me.
