### ISSUE TITLE
Replace Makefile with just

### ISSUE THREAD

**Issue by 0xh3rman** [gemwalletcom/core#139]
We don't use Makefile to build stuff, but just a shortcut to execute a bunch of commands

- `Makefile`
- `gemstone/Makefile`

Docs: https://just.systems/man/en

**Comment by kehiy** [comment]
@0xh3rman assign this to me.

**Comment by 0xh3rman** [comment]
This needs to test every command: including swift and kotlin binding (you have to install Xcode and Android studio etc), are you sure? 😃

**Comment by kehiy** [comment]
uh, I can test but about Xcode and swift part, I'm not sure.

**Comment by 0xh3rman** [comment]
I think you can start with the root `Makefile`

**Comment by kehiy** [comment]
@0xh3rman OK
