### ISSUE TITLE
Integration of Pactus Blockchain into Gem Wallet

### ISSUE THREAD

**Issue by b00f** [gemwalletcom/core#207]
Hello Gem Wallet Team,

We are interested in integrating the [Pactus blockchain](https://pactus.org/) into Gem Wallet and are seeking guidance on how to proceed with this implementation. Our team is available to assist with the development process.

One of the Pactus core developers, @kehiy, is actively contributing to Gem Wallet, which we believe can facilitate the integration process.

Could you please provide us with information on the following:

1. The required steps to integrate a new blockchain into Gem Wallet.
2. Any specific documentation or guidelines we should follow.
3. Key points of contact for technical support during the integration process.

We look forward to collaborating with you on this project and are eager to contribute to the Gem Wallet ecosystem.

**Comment by gemcoder21** [comment]
I did look into `Pactus` explorer and it does not seems like EVM compatible change (which would have been easy to integrate). At of right now all the chain implementations comes from [Wallet Core](https://github.com/trustwallet/wallet-core), you might have to integrate there first before we can enable on our side. 

Maybe 1-2 years fro now we will have infrastructure to support any chain inside Gem Core, but not as of right now.
