### ISSUE TITLE
makeFile

### ISSUE THREAD

**Issue by ShevoFirst** [gemwalletcom/core#262]
E0061
> this function takes 7 arguments but 1 argument was supplied

E0271
> expected `default` to be a fn item that returns `Option<ParsedData>`, but it returns `ParsedData`

E0599
> no method named `add` found for enum `std::option::Option`

after start install-typeshare, where i can download stable version of core?

**Comment by 0xh3rman** [comment]
This should be fixed, please try:
1. cargo install just
2. just install-typeshare
